server:
  port: 8081

spring:
  application:
    name: bff
  profiles:
    active: local
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: basic

logging:
  level:
    com.bff: INFO
    org.springframework.cloud.openfeign: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    openfeign:
      client:
        config:
          auth-service:
            url: http://auth-service:8080
          donation-service:
            url: http://donation-service:8080
          logistics-service:
            url: http://logistics-service:8080
          needs-service:
            url: http://needs-service:8080

server:
  port: 8080
